final String RESULT_SCREEN="/Result_SCREEN";
final String CAMERA_SCREEN="/CAMERA_SCREEN";
final String USER_INPUT_SCREEN="/USER_INPUT_SCREEN";
final String VIDEO_RECORDER_SCREEN="/VIDEO_RECORDER_SCREEN";