name: flutter_video_recorder_app
description: A new Flutter Video Recorder application.

version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  sound_stream: ^0.3.0
  rxdart: ^0.24.1
  cupertino_icons: ^0.1.2
  camera: ^0.8.1+5
  progress_dialog: ^1.2.4
  circular_countdown: ^2.1.0
  path_provider: ^2.0.2
  export_video_frame: ^0.0.5+4
  audioplayers: ^0.19.1
  google_speech: ^2.0.1
  logging: "^0.11.3+1"
  font_awesome_flutter: ^9.1.0
  dio: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true


  assets:
      - assets/audio/
      - assets/images/
      - assets/speech_to_text.json
module:
  androidX: true