name: flutter_video_recorder_app
description: A new Flutter Video Recorder application.

version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  camera: ^0.2.6
  circular_countdown: ^1.2.1
  path_provider: ^0.4.1
  video_player: ^0.7.2
  export_video_frame: ^0.0.5+4
  audioplayers: ^0.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true


  assets:
      - assets/audio/bell_audio.mp3
      - assets/images/ic_powered_by.png
      - assets/images/ic_switch_camera_3.png
      - assets/images/ic_no_video.png
      - assets/images/ic_play.png
      - assets/images/ic_stop_video.png
      - assets/images/ic_video_shutter.png
      - assets/images/eye_icon.png

module:
  androidX: true